# -*- coding: utf-8 -*-

{
    'name': 'Property Management',
    'version': '18.0.1.1.0',
    'summary': 'Management application',
    'sequence': 1,
    'description': "An application for managing your property",
    'category': 'Business',
    'depends': ['base', 'mail', 'contacts', 'account','web', 'website','portal'],
    'data': [
        'security/property_management_groups.xml',
        'security/property_rent_lease_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_data.xml',
        'data/property_properties_data.xml',
        'data/ir_cron_data.xml',
        'report/property_rent_lease_templates.xml',
        'report/property_rent_lease_reports.xml',
        'views/property_properties_views.xml',
        'views/property_rent_lease_views.xml',
        'views/property_intermediate_views.xml',
        'views/property_facility_views.xml',
        'views/res_partner_views.xml',
        'views/property_line_template.xml',
        'views/property_rent_website_template.xml',
        'wizard/make_property_rent_lease_views.xml',
        'views/property_management_website_portal.xml',
        'views/property_management_property_website.xml',
        'views/website_menus.xml',
        'views/property_menus.xml',
    ],
    'assets': {
        'web.assets_frontend': ['https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css',
                                'https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js',
                                'property_management/static/src/js/web_property_rent_lease.js',
                                'property_management/static/src/js/web_properties.js',
                                ],
        'web.assets_backend': ['property_management/static/src/js/action_manager.js', ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
